name: Check Script Diff(using /ee/maintained-apps/script-diff.sh)

on:
    push:
        branches:
            - workflow/check-script-diff

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
              
            - name: Get Changed Manifest Files # fetch the changed manifest files
              id: changed_files
              run: |
                echo "Fetching changed files..."
                git fetch origin workflow/check-script-diff
                git diff origin/workflow/check-script-diff HEAD \
                | grep -E 'ee/maintained-apps/(inputs|outputs)/.*\.json$' \
                > changed_manifests.txt
                cat changed_manifests.txt
                if [ ! -s changed_manifests.txt ]; then
                    echo "No changed manifest files found."
                    exit 0
                fi

# actually now i can see that the action is working on the push action, fine and returning the hello, github actions! message
# but now i want to check the script diff using the script-diff.sh script on some changed